# Generated by Django 5.2.4 on 2025-07-28 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(max_length=100, verbose_name="Doctor Name"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=100, verbose_name="Specialization"),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="License Number"
                    ),
                ),
                (
                    "availability",
                    models.JSONField(default=dict, verbose_name="Availability"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
                "db_table": "doctor_profiles",
            },
        ),
        migrations.CreateModel(
            name="NurseProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nurse_name",
                    models.CharField(max_length=100, verbose_name="Nurse Name"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=100, verbose_name="Specialization"),
                ),
                (
                    "license_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="License Number"
                    ),
                ),
                (
                    "availability",
                    models.JSONField(default=dict, verbose_name="Availability"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nurse_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nurse Profile",
                "verbose_name_plural": "Nurse Profiles",
                "db_table": "nurse_profiles",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(max_length=100, verbose_name="Patient Name"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("outpatient", "Outpatient"),
                            ("inpatient", "Inpatient"),
                            ("emergency", "Emergency"),
                        ],
                        default="outpatient",
                        max_length=20,
                        verbose_name="Patient Type",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
                "db_table": "patient_profiles",
            },
        ),
    ]
