# Generated by Django 5.2.4 on 2025-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userprofile_managers_alter_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(default="", max_length=100, verbose_name="Full Name"),
        ),
    ]
