# Generated by Django 5.2.4 on 2025-08-10 11:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("operations", "0001_initial"),
        ("users", "0002_doctorprofile_nurseprofile_patientprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "communication_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "communication_type",
                    models.CharField(
                        choices=[
                            ("patient_doctor", "Patient-Doctor"),
                            ("patient_nurse", "Patient-Nurse"),
                            ("doctor_nurse", "Doctor-Nurse"),
                            ("doctor_doctor", "Doctor-Doctor"),
                            ("nurse_nurse", "Nurse-Nurse"),
                            ("general", "General"),
                        ],
                        max_length=20,
                        verbose_name="Communication Type",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priority",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiated_communications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="communications",
                        to="operations.appointment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Communication",
                "verbose_name_plural": "Communications",
                "db_table": "communications",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunicationParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("initiator", "Initiator"),
                            ("participant", "Participant"),
                            ("cc", "CC"),
                            ("bcc", "BCC"),
                        ],
                        default="participant",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "communication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communications.communication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "communication_participants",
                "unique_together": {("communication", "user")},
            },
        ),
        migrations.AddField(
            model_name="communication",
            name="participants",
            field=models.ManyToManyField(
                related_name="participated_communications",
                through="communications.CommunicationParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MedicalRecordRequest",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("complete_record", "Complete Medical Record"),
                            ("lab_results", "Laboratory Results"),
                            ("prescriptions", "Prescriptions"),
                            ("diagnosis", "Diagnosis Reports"),
                            ("treatment_plan", "Treatment Plans"),
                            ("vaccination_record", "Vaccination Records"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "specific_records",
                    models.TextField(
                        blank=True, null=True, verbose_name="Specific Records Requested"
                    ),
                ),
                (
                    "reason_for_request",
                    models.TextField(verbose_name="Reason for Request"),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Urgency Level",
                    ),
                ),
                (
                    "preferred_delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("portal", "Patient Portal"),
                            ("physical_copy", "Physical Copy"),
                            ("fax", "Fax"),
                        ],
                        default="portal",
                        max_length=20,
                        verbose_name="Preferred Delivery Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Administrative Notes"
                    ),
                ),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Doctor Notes"
                    ),
                ),
                ("requested_date", models.DateTimeField(auto_now_add=True)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_record_requests",
                        to="users.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_record_requests",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Record Request",
                "verbose_name_plural": "Medical Record Requests",
                "db_table": "medical_record_requests",
                "ordering": ["-requested_date"],
            },
        ),
        migrations.AddField(
            model_name="communication",
            name="related_record_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="communications",
                to="communications.medicalrecordrequest",
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("voice", "Voice"),
                            ("video", "Video"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(verbose_name="Message Content")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="communication_attachments/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "mp3",
                                    "mp4",
                                    "txt",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "attachment_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("attachment_size", models.IntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "communication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="communications.communication",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="communications.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("record_request", "Medical Record Request"),
                            ("message", "New Message"),
                            ("communication", "New Communication"),
                            ("status_update", "Status Update"),
                            ("reminder", "Reminder"),
                            ("system", "System Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_communication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communications.communication",
                    ),
                ),
                (
                    "related_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communications.message",
                    ),
                ),
                (
                    "related_record_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="communications.medicalrecordrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="communications.message",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "message_recipients",
                "unique_together": {("message", "recipient")},
            },
        ),
    ]
