# Generated by Django 5.2.4 on 2025-08-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_doctorprofile_nurseprofile_patientprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("appointment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("follow_up", "Follow-up"),
                            ("emergency", "Emergency"),
                            ("routine", "Routine Check-up"),
                        ],
                        max_length=20,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
                ("reason", models.TextField()),
                ("queue_number", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="users.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["appointment_date", "appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="ClinicInventory",
            fields=[
                ("inventory_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=100)),
                ("current_stock", models.IntegerField()),
                ("minimum_stock", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiry_date", models.DateField()),
                ("batch_number", models.CharField(max_length=50)),
                ("supplier", models.CharField(max_length=100)),
                ("last_restocked", models.DateTimeField()),
                ("usage_pattern", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nurse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="users.nurseprofile",
                    ),
                ),
            ],
            options={
                "db_table": "clinic_inventory",
                "ordering": ["item_name"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("record_date", models.DateField()),
                ("diagnosis", models.TextField()),
                ("symptoms", models.TextField()),
                ("treatment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="users.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "db_table": "medical_records",
                "ordering": ["record_date"],
            },
        ),
        migrations.CreateModel(
            name="QueueManagement",
            fields=[
                ("queue_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "queue_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("walk_in", "Walk-in"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                    ),
                ),
                ("queue_date", models.DateField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("patient_serving", models.IntegerField(default=0)),
                ("total_patients", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="users.patientprofile",
                    ),
                ),
            ],
            options={
                "db_table": "queue_management",
                "ordering": ["queue_date", "created_at"],
            },
        ),
    ]
